### ISSUE TITLE
metadata/pkgcheck.conf not parsed

### ISSUE THREAD

**Issue by ZeroChaos-** [pkgcore/pkgcheck#576]
per https://pkgcore.github.io/pkgcheck/man/pkgcheck.html#config-file-support I was expecting ${some_ebuild_repo}/metadata/pkgcheck.conf to be parsed as a pkgcheck config file.

My system has three repos defined
```
Repositories:

gentoo
    location: /var/db/repos/gentoo
    sync-type: rsync
    sync-uri: rsync://rsync.gentoo.org/gentoo-portage
    priority: -1000
    volatile: True
    sync-rsync-verify-max-age: 24
    sync-rsync-verify-metamanifest: yes
    sync-rsync-extra-opts: 
    sync-rsync-verify-jobs: 1

maintainer-zero
    location: /usr/local/portage
    masters: gentoo
    priority: 0
    volatile: True

pentoo
    location: /home/zero/development/pentoo/pentoo-overlay
    sync-openpgp-key-refresh: no
    sync-type: git
    sync-uri: https://github.com/pentoo/pentoo-overlay.git
    masters: gentoo
    priority: 49
    volatile: True
    sync-git-verify-commit-signature: true
```

When I run pkgcheck it doesn't seem to attempt to read the metadata/pkgcheck.conf from any of them:
```
zero@theprophet metadata % strace pkgcheck scan --repo pentoo -C PentooCI --net --tasks=32 --jobs=32 2>&1 | grep pkgcheck.conf 
openat(AT_FDCWD, "/etc/python-exec/pkgcheck.conf", O_RDONLY) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/usr/share/pkgcheck/pkgcheck.conf", {st_mode=S_IFREG|0644, st_size=717, ...}, 0) = 0
openat(AT_FDCWD, "/usr/share/pkgcheck/pkgcheck.conf", O_RDONLY|O_CLOEXEC) = 3
newfstatat(AT_FDCWD, "/etc/pkgcheck/pkgcheck.conf", 0x7fff2fb26088, 0) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/home/zero/.config/pkgcheck/pkgcheck.conf", 0x7fff2fb26088, 0) = -1 ENOENT (No such file or directory)
```
But one does exist:
```
zero@theprophet metadata % cat /home/zero/development/pentoo/pentoo-overlay/metadata/pkgcheck.conf                                          
[CHECKSETS]
PentooCI =
  BadDependency
```
